#!/usr/bin/env python3
"""Generate shaders.h from the upstream spicetify-visualizer GLSL.

The shaders are lifted verbatim from src/shaders/ncs-visualizer/*.ts; the only
edit is the version directive, because we run on desktop OpenGL rather than
WebGL2 (GLSL ES 3.00 and GLSL 3.30 core are otherwise compatible here).
"""
import pathlib
import re
import sys

SRC = pathlib.Path(sys.argv[1]) / "src/shaders/ncs-visualizer"
OUT = pathlib.Path(sys.argv[2])

STAGES = ["particle", "dot", "blur", "finalize"]


def extract(path: pathlib.Path, name: str) -> str:
    text = path.read_text()
    m = re.search(r"export const %s = `(.*?)`;" % name, text, re.S)
    if not m:
        raise SystemExit(f"could not find {name} in {path}")
    src = m.group(1)
    src = src.replace("#version 300 es", "#version 330 core")
    # precision qualifiers are a GLSL ES thing and are no-ops on desktop GLSL,
    # where Mesa's core-profile parser rejects them outright
    src = re.sub(r"^\s*precision\s+\w+\s+\w+\s*;\s*$\n?", "", src, flags=re.M)
    # implicitly sized arrays are shakier on desktop GLSL than in WebGL2
    src = src.replace("const float GRADIENTS_3D[] = float[](",
                      "const float GRADIENTS_3D[256] = float[256](")
    if name == "fragmentShader" and path.name == "finalize.ts":
        src = patch_finalize(src)
    return src.strip("\n")


def patch_finalize(src: str) -> str:
    """Allow the bloom to be tinted separately from the dots.

    With uGlowColor == uOutputColor the mix collapses to the original
    `outColor = vec4(fragOutputColor * value, value)` exactly, so the default
    behaviour is bit-for-bit the upstream one.
    """
    old = """    float value = max(texture(uBlurredTexture, fragUV).r, texture(uOriginalTexture, fragUV).r);
    outColor = vec4(fragOutputColor * value, value);"""
    new = """    float blurred = texture(uBlurredTexture, fragUV).r;
    float original = texture(uOriginalTexture, fragUV).r;

    float value = max(blurred, original);
    vec3 tint = mix(uGlowColor, fragOutputColor, original / max(value, 1e-4));

    outColor = vec4(tint * value, value);"""
    if old not in src:
        raise SystemExit("finalize.ts no longer matches the expected body")
    src = src.replace(old, new)
    return src.replace("uniform sampler2D uBlurredTexture;",
                       "uniform vec3 uGlowColor;\n\nuniform sampler2D uBlurredTexture;")


def cpp_raw(name: str, src: str) -> str:
    return 'static const char *const %s = R"GLSL(%s\n)GLSL";\n' % (name, src)


parts = [
    "// GENERATED by gen_shaders.py -- do not edit.",
    "// Source: https://github.com/Konsl/spicetify-visualizer"
    " (src/shaders/ncs-visualizer)",
    "#pragma once",
    "",
]
for stage in STAGES:
    path = SRC / f"{stage}.ts"
    for kind, suffix in (("vertexShader", "Vert"), ("fragmentShader", "Frag")):
        parts.append(cpp_raw(f"k{stage.capitalize()}{suffix}", extract(path, kind)))

OUT.write_text("\n".join(parts))
print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
